# Generated by Django 5.1.1 on 2024-09-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='is_veg',
            new_name='is_complete',
        ),
        migrations.AddField(
            model_name='task',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
